language: python
python:
   - "2.7"
before_install:
  pip install codecov
# Dependencies
install: "pip install -r requirements.txt"
# Run test
script:
   - coverage run --source=pymangal ./tests.py
   - coverage report -m
after_success:
   coveralls --verbose
   codecov
