language: python
python:
   - "2.6"
   - "2.7"
# Dependencies
install: "pip install -r requirements.txt"
# Run test
script:
   - coverage run --source=pymangal ./test_pymangal.py
   - coverage report -m
after_success:
   coveralls --verbose
